name       : python-tomli
version    : 2.0.1
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/t/tomli/tomli-2.0.1.tar.gz : de526c12914f0c550d15924c62d72abc48d6fe7364aa87328337a31007fe8a4f
homepage   : https://github.com/hukkin/tomli
license    : MIT
component  : programming.python
summary    : A little TOML parser for Python
description: |
    Tomli is a Python library for parsing TOML.
networking : yes
builddeps  :
    - python-build
    - python-flit
    - python-installer
    - python-packaging
    - python-wheel
    - python-pyproject2setuppy
    - python3-devel
build      : |
    # Installing flip as user for now to skip packaging 5 new python packages.
    export PYTHONUSERBASE=$workdir
    export PATH=$PATH:$workdir/bin/
    python3 -m pip install --user flip
    python3 -m pip wheel --no-deps .
install    : |
    unset PYTHONUSERBASE
    python3 -m pip install --root=%installroot% --no-deps *.whl
